//Model
let cardHTML = "";

const model = {
    movies: [
      {
        title: "Deadpool",
        releaseDate: "2024",
        genre: "Action, Comedy",
        poster: "Assets/$_57.jfif",
        rating: 945,
      },
      {
        title: "Blade Runner",
        releaseDate: "2008",
        genre: "Action",
        poster: "Assets/1.jpg",
        rating: 923,
      },
      {
        title: "Raw",
        releaseDate: "2014",
        genre: "Adventure",
        poster: "Assets/1131w-L8p5tGjRpj8.webp",
        rating: 443,
      },
      {
        title: "Walk Alone",
        releaseDate: "2019",
        genre: "Thriller",
        poster: "Assets/1131w-YZ-0GJ13Nc8.webp",
        rating: 874,
      },
      {
        title: "1917",
        releaseDate: "2019",
        genre: "War",
        poster: "Assets/1917-british-movie-poster-md.jpg",
        rating: 996,
      },
      {
        title: "Witchcock Psyhco",
        releaseDate: "1972",
        genre: "Crime",
        poster: "Assets/28.jpg",
        rating: 753,
      },
      {
        title: "James Bond - Quantum Of Silence",
        releaseDate: "1999",
        genre: "Action, Spy",
        poster: "Assets/59001.webp",
        rating: 867,
      },
      {
        title: "James Bond - Live And Let Die",
        releaseDate: "1996",
        genre: "Action, Spy",
        poster: "Assets/59837.webp",
        rating: 966,
      },
      {
        title: "Scream",
        releaseDate: "2006",
        genre: "Thriller, Comedy",
        poster: "Assets/61L3eGk45kL._AC_UF894,1000_QL80_.jpg",
        rating: 926,
      },
      {
        title: "65 Million Years Ago",
        releaseDate: "2012",
        genre: "Action",
        poster: "Assets/65.jfif",
        rating: 296,
      },
      {
        title: "Shoot'em Up",
        releaseDate: "1994",
        genre: "Action",
        poster: "Assets/69eb2e87e012ec13b985b6b9d4aec99d.jpg",
        rating: 325,
      },
      {
        title: "Coded",
        releaseDate: "2023",
        genre: "Documentary",
        poster: "Assets/7.-Coded-content.jpg",
        rating: 296,
      },
      {
        title: "Avatar",
        releaseDate: "2009",
        genre: "Science Fiction",
        poster: "Assets/Avatar_7ce699c0-ce5d-40b8-bb35-13fee557b8d7_large.webp",
        rating: 846,
      },
      {
        title: "Black Panther",
        releaseDate: "2018",
        genre: "Action",
        poster: "Assets/blackpanther.jfif",
        rating: 783,
      },
      {
        title: "Zoolander",
        releaseDate: "2023",
        genre: "Comedy",
        poster: "Assets/DB_032-671x1024.jpg",
        rating: 794,
      },
      {
        title: "Little Miss Sunshine",
        releaseDate: "2023",
        genre: "Romance",
        poster: "Assets/download.jfif",
        rating: 656,
      },
      {
        title: "Dune",
        releaseDate: "2021",
        genre: "Science Fiction",
        poster: "Assets/Dune-movie-poster.webp",
        rating: 654,
      },
      {
        title: "Star Wars The Phantom Menace",
        releaseDate: "2003",
        genre: "Sci-Fi",
        poster: "Assets/f3bi3nx1i7a61.jpg",
        rating: 782,
      },
      {
        title: "Furiosa",
        releaseDate: "2024",
        genre: "Action",
        poster: "Assets/Furiosa-poster-Matt-Robot.webp",
        rating: 490,
      },
      {
        title: "Horizon",
        releaseDate: "2023",
        genre: "Adventure",
        poster: "Assets/HRZN1_Character_Sam_VERT_MAIN_2764x4096_DOM.webp",
        rating: 620,
      },
      {
        title: "Drive",
        releaseDate: "2023",
        genre: "Action Adventure",
        poster: "Assets/il_570xN.3393446498_ezqg.webp",
        rating: 710,
      },
      {
        title: "Elf",
        releaseDate: "2004",
        genre: "Comedy",
        poster: "Assets/il_570xN.3517804383_nutl.webp",
        rating: 850,
      },
      {
        title: "Scream",
        releaseDate: "2023",
        genre: "Horror",
        poster: "Assets/scream.jpg",
        rating: 430,
      },
      {
        title: "12 Angry Men",
        releaseDate: "2023",
        genre: "Drama",
        poster: "Assets/12angrymen.jpg",
        rating: 900,
      },
      {
        title: "Black Mirror",
        releaseDate: "2023",
        genre: "Action",
        poster: "Assets/blackmirror.webp",
        rating: 300,
      },
      {
        title: "X-Men",
        releaseDate: "2023",
        genre: "Fantasy, Heroes",
        poster: "Assets/xmen.webp",
        rating: 575,
      },
      {
        title: "127 Hours",
        releaseDate: "2023",
        genre: "Adventure",
        poster: "Assets/127hours.jpg",
        rating: 650,
      },
      {
        title: "Lamb",
        releaseDate: "2023",
        genre: "Adventure",
        poster: "Assets/lamb.jpg",
        rating: 440,
      },
      {
        title: "Parasite",
        releaseDate: "2023",
        genre: "Thriller",
        poster: "Assets/parasite.jpg",
        rating: 920,
      },
      {
        title: "The Amusement Park",
        releaseDate: "2023",
        genre: "Horror",
        poster: "Assets/amusement.jpg",
        rating: 380,
      },
      {
        title: "Possessor",
        releaseDate: "2023",
        genre: "Horror",
        poster: "Assets/images-w1400.jpg",
        rating: 500,
      },
      {
        title: "Creed 3",
        releaseDate: "2023",
        genre: "Action, Fighter",
        poster: "Assets/images.jfif",
        rating: 710,
      },
      {
        title: "Interstellar",
        releaseDate: "2014",
        genre: "Science Fiction",
        poster: "Assets/interstellar_2014_advance_original_film_art_682852f2-23f6-46de-a1db-4029d5b6f0b4_5000x.jpg",
        rating: 940,
      },
      {
        title: "Jaws",
        releaseDate: "1975",
        genre: "Thriller",
        poster: "Assets/jaws-alternative-movie-poster-movie-poster-boy.jpg",
        rating: 870,
      },
      {
        title: "Jaws (Version 2)",
        releaseDate: "1975",
        genre: "Thriller",
        poster: "Assets/jaws-andrew-swainson-movie-poster.webp",
        rating: 780,
      },
      {
        title: "John Wick",
        releaseDate: "2014",
        genre: "Action",
        poster: "Assets/JohnWick-KeanuReeves-HollywoodEnglishActionMoviePoster-2.webp",
        rating: 930,
      },
      {
        title: "Jojo Rabbit",
        releaseDate: "2019",
        genre: "Comedy",
        poster: "Assets/jojo-rabbit.jpg",
        rating: 860,
      },
      {
        title: "Joker",
        releaseDate: "2019",
        genre: "Drama",
        poster: "Assets/joker.jfif",
        rating: 950,
      },
      {
        title: "Little Fish",
        releaseDate: "2020",
        genre: "Romance",
        poster: "Assets/Little-Fish2.webp",
        rating: 540,
      },
      {
        title: "Logan",
        releaseDate: "2017",
        genre: "Action",
        poster: "Assets/logan-2017.webp",
        rating: 880,
      },
      {
        title: "Moon",
        releaseDate: "2009",
        genre: "Science Fiction",
        poster: "Assets/moon.jpg",
        rating: 710,
      },
      {
        title: "Moonlight",
        releaseDate: "2016",
        genre: "Drama",
        poster: "Assets/moonlight_0.jpg",
        rating: 720,
      },
      {
        title: "James Bond - Skyfall",
        releaseDate: "2023",
        genre: "Action, Spy",
        poster: "Assets/movie-poster-12.jpg",
        rating: 850,
      },
      {
        title: "The Terror of the Deep",
        releaseDate: "2023",
        genre: "Horror",
        poster: "Assets/movie-poster-the-terror-of-the-deep.jpg",
        rating: 640,
      },
      {
        title: "The Shade",
        releaseDate: "2023",
        genre: "Drama",
        poster: "Assets/MV5BMjQxMDgzNmItOWUyNi00YzYxLWI3MjgtM2Y4ZDg1YjkyMTA3XkEyXkFqcGc@._V1_QL75_UX480_.jpg",
        rating: 700,
      },
      {
        title: "Now You See Me 2",
        releaseDate: "2016",
        genre: "Thriller",
        poster: "Assets/nysm2-official-quad-scaled.jpg",
        rating: 750,
      },
      {
        title: "Oppenheimer",
        releaseDate: "2023",
        genre: "Biography",
        poster: "Assets/oppenheimer.jfif",
        rating: 900,
      },
      {
        title: "Harry Potter and the Philosopher's Stone",
        releaseDate: "2001",
        genre: "Fantasy",
        poster: "Assets/philosophers-stone-20-years-of-movie-magic-hagrid-poster.jpg",
        rating: 880,
      },
      {
        title: "Classic Movie Collection",
        releaseDate: "2023",
        genre: "Compilation",
        poster: "Assets/Polish-movie-posters-rocky-thegodfather-apocalypsenow-alienandaliens-taxidriver-termiantor-poland-cinema-sabukaru-online-magazine-tokyo34.jpg",
        rating: 770,
      },
      {
        title: "Black Adam",
        releaseDate: "2023",
        genre: "Action",
        poster: "Assets/posd1_1.webp",
        rating: 650,
      },
      {
        title: "Mean Streets",
        releaseDate: "1973",
        genre: "Crime",
        poster: "Assets/posters-1-mean-streets.jpg",
        rating: 810,
      },
      {
        title: "Radhe Shyam",
        releaseDate: "2022",
        genre: "Romance",
        poster: "Assets/radhe-shyam.avif",
        rating: 720,
      },
      {
        title: "Inside Out",
        releaseDate: "2015",
        genre: "Animation",
        poster: "Assets/rs_634x884-160115101546-634-inside-out-parody-poster.webp",
        rating: 850,
      },
      {
        title: "Spider-Man: Far From Home",
        releaseDate: "2019",
        genre: "Action",
        poster: "Assets/spider-man-far-from-home-official-movie-posters_ex7e.1080.webp",
        rating: 800,
      },
      {
        title: "Spies in Disguise",
        releaseDate: "2019",
        genre: "Animation",
        poster: "Assets/spies-in-the-poster-1_1600x.webp",
        rating: 720,
      },
      {
        title: "Star Wars: Rogue One",
        releaseDate: "2016",
        genre: "Science Fiction",
        poster: "Assets/starWarsRogueOne.jpg",
        rating: 830,
      },
      {
        title: "Suspiria",
        releaseDate: "2018",
        genre: "Horror",
        poster: "Assets/suspiria-posters.webp",
        rating: 690,
      },
      {
        title: "The Batman",
        releaseDate: "2022",
        genre: "Action",
        poster: "Assets/The-Batman-2.webp",
        rating: 870,
      },
      {
        title: "The Batman (Unmask The Truth)",
        releaseDate: "2022",
        genre: "Action",
        poster: "Assets/The-Batman-4.webp",
        rating: 860,
      },
      {
        title: "Titanic",
        releaseDate: "1997",
        genre: "Romance",
        poster: "Assets/titanic.webp",
        rating: 950,
      },
      {
        title: "Abigail",
        releaseDate: "2023",
        genre: "Drama",
        poster: "Assets/unnamed.jpg",
        rating: 720,
      },
      {
        title: "Longlegs",
        releaseDate: "2023",
        genre: "Thriller",
        poster: "Assets/longlegs.jpg",
        rating: 650,
      },
      {
        title: "Civil War",
        releaseDate: "2024",
        genre: "Action",
        poster: "Assets/civilwar.webp",
        rating: 800,
      },
      {
        title: "Thor - The Dark World",
        releaseDate: "2023",
        genre: "Hero",
        poster: "Assets/rico_thor2.jpg",
        rating: 740,
      },
      {
        title: "Despicable Me 4",
        releaseDate: "2023",
        genre: "Animation",
        poster: "Assets/gru4.jpg",
        rating: 780,
      },
      {
        title: "Kingdom Of The Apes",
        releaseDate: "2023",
        genre: "Action",
        poster: "Assets/kingdomoftheapes.jpg",
        rating: 720,
      },
      {
        title: "Speak No Evil",
        releaseDate: "2023",
        genre: "Thriller",
        poster: "Assets/Speaknoevil.jpg",
        rating: 670,
      },
      {
        title: "Uri: The Surgical Strike",
        releaseDate: "2019",
        genre: "Action",
        poster: "Assets/Uri_-_Hows_The_Josh_-_Bollywood_Patriotic_Hindi_Movie_Poster_117ca0f6-c747-46a7-91e7-c794235e4906.jpg",
        rating: 750,
      },
      {
        title: "Vengeance",
        releaseDate: "2022",
        genre: "Thriller",
        poster: "Assets/Vengeance.webp",
        rating: 720,
      },
      {
        title: "Vice",
        releaseDate: "2018",
        genre: "Biography",
        poster: "Assets/vice-web.jpg",
        rating: 780,
      },
      {
        title: "West Side Story",
        releaseDate: "2021",
        genre: "Musical",
        poster: "Assets/west-side-story-poster-print.jpg",
        rating: 820,
      },
      {
        title: "Uncharted",
        releaseDate: "2023",
        genre: "Action, Adventure",
        poster: "Assets/what-has-happened-to-movie-posters-v0-tm2y16wnnhb81.jpg",
        rating: 740,
      },
      {
        title: "Uncharted",
        releaseDate: "2023",
        genre: "Action, Adventure",
        poster: "Assets/what-has-happened-to-movie-posters-v0-tm2y16wnnhb81.jpg",
        rating: 740,
    },
    {
        title: "Wonder Woman",
        releaseDate: "2017",
        genre: "Action",
        poster: "Assets/wonder-woman_adv_c_ds_os-891437.webp",
        rating: 800,
    },
    {
        title: "Wonka",
        releaseDate: "2023",
        genre: "Fantasy",
        poster: "Assets/WONKA_INSTA_VERT_Father_Julius_1638x2048_DOM-1.webp",
        rating: 750,
    },
    {
        title: "Tigertrail",
        releaseDate: "2023",
        genre: "Adventure",
        poster: "Assets/X-twitter_EVrDfLIXkAIyhju.avif",
        rating: 720,
    },
    {
        title: "The Front Line",
        releaseDate: "2007",
        genre: "War",
        poster: "Assets/the-front-line-in-the-poster-1_1600x.webp",
        rating: 780,
    },
    {
        title: "The Gladiator",
        releaseDate: "2009",
        genre: "Adventure",
        poster: "Assets/thegladiator.jpg",
        rating: 850,
    },

    {
      title: "Miracles from Heaven",
      releaseDate: "2016",
      genre: "Drama",
      poster: "Assets/miraclesfromheaven.jpg",
      rating: 880,
  },
  {
    title: "Fifty Shades Of Grey",
    releaseDate: "2015",
    genre: "Romance",
    poster: "Assets/fiftyshades.jpg",
    rating: 748,
},

       
    ]
  };
  